export const GETCARDS = "GETCARDS";
export const NORESULTS = "NORESULTS";
export const ISLOADING = "ISLOADING";
export const SHOWCONTENTPOLICY = "SHOWCONTENTPOLICY";

export const CARD_FLIPPED_TRUE = "CARD_FLIPPED_TRUE";
export const CARD_FLIPPED_FALSE = "CARD_FLIPPED_FALSE";