// export const WHITE = "WHITE";
// export const BLUE = "BLUE";
// export const BLACK = "BLACK";
// export const RED = "RED";
// export const GREEN = "GREEN";
// export const COLORLESS = "COLORLESS";
// export const LANDS = "LANDS";
export const GETCARDS = "GETCARDS";
export const NORESULTS = "NORESULTS";